- Dev:
  - github:
    - icon: github.png
      href: https://github.com/mattcl
  - crates.io:
    - icon: rust.png
      href: https://crates.io

- Social:
  - icon: reddit.png
    href: https://old.reddit.com
