- CI/CD:
  - Argo CD:
      icon: argocd.png
      href: https://argocd.hl.ancalagon.black
      ping: https://argocd.hl.ancalagon.black
      description: GitOps deploys for kubernetes cluster

- Cluster tools:
  - traefik:
      icon: traefik.png
      href: https://traefik.hl.ancalagon.black
      ping: https://traefik.hl.ancalagon.black
      description: traefik reverse proxy routing dashboard
  - scrutiny:
      icon: scrutiny-light.png
      href: http://chiark.home:8080
      ping: http://chiark.home:8080
      description: SMART disk monitoring dashboard

- Networking:
  - pi-hole:
      icon: pi-hole.png
      href: http://192.168.1.193/admin
      ping: http://192.168.1.193/admin
      description: DNS server and adblocker
