- Media:
  - Jellyfin:
      icon: jellyfin.png
      href: http://chiark.home:8096
      ping: http://chiark.home:8096
      description: Media server.

  - Stump:
      icon: /icons/stump-logo--irregular.png
      href: https://stump.hl.ancalagon.black
      ping: https://stump.hl.ancalagon.black
      description: Digital book, comic, and OPDS server.

  - tandoor:
      icon: tandoor.png
      href: https://tandoor.ancalagon.black
      ping: https://tandoor.ancalagon.black
      description: Recipe database and meal planning.

  - Synology NAS:
      icon: synology-dsm
      href: http://sleeper-service.home:5000
      ping: http://sleeper-service.home:5000
      description: Primary NAS.

  - Prowlarr:
      icon: prowlarr.png
      href: https://prowlarr.hl.ancalagon.black
      ping: https://prowlarr.hl.ancalagon.black
      description: Indexer management.

  - Jellyseerr:
      icon: jellyseerr.png
      href: https://jellyseerr.hl.ancalagon.black
      ping: https://jellyseerr.hl.ancalagon.black
      description: Media requests.
      widget:
        type: jellyseerr
        url: https://jellyseerr.hl.ancalagon.black
        key: "{{HOMEPAGE_VAR_JELLYSEERR_KEY}}"
        fields: ["approved", "available"]

  - Radarr:
      icon: radarr-light.png
      href: https://radarr.hl.ancalagon.black
      ping: https://radarr.hl.ancalagon.black
      description: Movie requests.
      widget:
        type: radarr
        url: https://radarr.hl.ancalagon.black
        key: "{{HOMEPAGE_VAR_RADARR_KEY}}"
        fields: ["wanted", "missing", "queued"]

  - Sonarr:
      icon: sonarr.png
      href: https://sonarr.hl.ancalagon.black
      ping: https://sonarr.hl.ancalagon.black
      description: TV show requests.
      widget:
        type: sonarr
        url: https://sonarr.hl.ancalagon.black
        key: "{{HOMEPAGE_VAR_SONARR_KEY}}"
        fields: ["wanted", "queued"]

  - Readarr:
      icon: readarr.png
      href: https://readarr.hl.ancalagon.black
      ping: https://readarr.hl.ancalagon.black
      description: Book requests.
      widget:
        type: readarr
        url: https://readarr.hl.ancalagon.black
        key: "{{HOMEPAGE_VAR_READARR_KEY}}"
        fields: ["wanted", "queued"]

- Services:
  - 2FA:
      icon: mdi-two-factor-authentication
      href: https://2fa.hl.ancalagon.black
      ping: https://2fa.hl.ancalagon.black
      description: Internal 2FA generator.

  - Concourse Papercode:
      icon: concourse.png
      href: http://ci.papercode.net:8080
      ping: http://ci.papercode.net:8080
      description: Papercode CI server.

  - ntfy:
      icon: ntfy-light.png
      href: https://ntfy.hl.ancalagon.black
      ping: https://ntfy.hl.ancalagon.black
      description: Internal Pub/Sub notifications.

  - pi-hole:
      icon: pi-hole.png
      href: http://192.168.1.193/admin
      ping: http://192.168.1.193/admin
      description: DNS server and adblocker.
      widget:
        type: pihole
        url: http://192.168.1.193
        key: "{{HOMEPAGE_VAR_PIHOLE_TOKEN}}"

- Cluster Tools:
  - Argo CD:
      icon: argocd.png
      href: https://argocd.hl.ancalagon.black
      ping: https://argocd.hl.ancalagon.black
      description: GitOps deploys for kubernetes cluster.
  - traefik-internal:
      icon: traefik.png
      href: https://traefik.hl.ancalagon.black
      ping: https://traefik.hl.ancalagon.black
      description: internal reverse proxy routing dashboard.
  - traefik-external:
      icon: traefik.png
      href: https://traefik-external.ancalagon.black
      ping: https://traefik-external.ancalagon.black
      description: external reverse proxy routing dashboard.
  - scrutiny:
      icon: scrutiny-light.png
      href: http://chiark.home:8080
      ping: http://chiark.home:8080
      description: SMART disk monitoring dashboard.
      widget:
        type: scrutiny
        url: http://chiark.home:8080

- Download Clients:
  - MeTube:
      icon: metube.png
      href: https://metube.hl.ancalagon.black
      ping: https://metube.hl.ancalagon.black
      description: YouTube (and others) downloader.

  - qbittorrent:
      icon: qbittorrent.png
      href: http://chiark.home:9077
      ping: http://chiark.home:9077
      description: Torrent client.
      widget:
        type: qbittorrent
        url: http://chiark.home:9077
        username: "{{HOMEPAGE_VAR_QBITTORRENT_USER}}"
        password: "{{HOMEPAGE_VAR_QBITTORRENT_PASS}}"

  - SABnzbd:
      icon: sabnzbd-alt.png
      href: https://sabnzbd.hl.ancalagon.black
      ping: https://sabnzbd.hl.ancalagon.black
      description: Usenet client.
      widget:
        type: sabnzbd
        url: https://sabnzbd.hl.ancalagon.black
        key: "{{HOMEPAGE_VAR_SABNZBD_KEY}}"
