- Media:
  - Jellyfin:
      icon: jellyfin.png
      href: http://chiark.home:8096
      ping: http://chiark.home:8096
      description: Media server.

  - Stump:
      icon: /icons/stump-logo--irregular.png
      href: https://stump.hl.ancalagon.black
      ping: https://stump.hl.ancalagon.black
      description: Digital book, comic, and OPDS server.

  - tandoor:
      icon: tandoor.png
      href: https://tandoor.ancalagon.black
      ping: https://tandoor.ancalagon.black
      description: Recipe database and meal planning.

- Media Support:
  - Jellyseerr:
      icon: jellyseerr.png
      href: https://jellyseerr.hl.ancalagon.black
      ping: https://jellyseerr.hl.ancalagon.black
      description: Media requests.
      widget:
        type: jellyseerr
        url: https://jellyseerr.hl.ancalagon.black
        key: "{{HOMEPAGE_VAR_JELLYSEERR_KEY}}"

  - MeTube:
      icon: metube.png
      href: https://metube.hl.ancalagon.black
      ping: https://metube.hl.ancalagon.black
      description: YouTube (and others) downloader.

  - Radarr:
      icon: radarr-light.png
      href: https://radarr.hl.ancalagon.black
      ping: https://radarr.hl.ancalagon.black
      description: Movie requests.

  - Sonarr:
      icon: sonarr.png
      href: https://sonarr.hl.ancalagon.black
      ping: https://sonarr.hl.ancalagon.black
      description: TV show requests.

  - SABnzbd:
      icon: sabnzbd-alt.png
      href: https://sabnzbd.hl.ancalagon.black
      ping: https://sabnzbd.hl.ancalagon.black
      description: Usenet client.
      widget:
        type: sabnzbd
        url: https://sabnzbd.hl.ancalagon.black
        key: "{{HOMEPAGE_VAR_SABNZBD_KEY}}"

- Services:
  - 2FA:
      icon: mdi-two-factor-authentication
      href: https://2fa.hl.ancalagon.black
      ping: https://2fa.hl.ancalagon.black
      description: Internal 2FA generator.

  - Concourse Papercode:
      icon: concourse.png
      href: http://ci.papercode.net:8080
      ping: http://ci.papercode.net:8080
      description: Papercode CI server.

  - ntfy:
      icon: ntfy-light.png
      href: https://ntfy.hl.ancalagon.black
      ping: https://ntfy.hl.ancalagon.black
      description: Internal Pub/Sub notifications.

- Cluster tools:
  - Argo CD:
      icon: argocd.png
      href: https://argocd.hl.ancalagon.black
      ping: https://argocd.hl.ancalagon.black
      description: GitOps deploys for kubernetes cluster.
  - traefik-internal:
      icon: traefik.png
      href: https://traefik.hl.ancalagon.black
      ping: https://traefik.hl.ancalagon.black
      description: internal reverse proxy routing dashboard.
  - traefik-external:
      icon: traefik.png
      href: https://traefik-external.ancalagon.black
      ping: https://traefik-external.ancalagon.black
      description: external reverse proxy routing dashboard.
  - scrutiny:
      icon: scrutiny-light.png
      href: http://chiark.home:8080
      ping: http://chiark.home:8080
      description: SMART disk monitoring dashboard.
      widget:
        type: scrutiny
        url: http://chiark.home:8080

- Support:
  - pi-hole:
      icon: pi-hole.png
      href: http://192.168.1.193/admin
      ping: http://192.168.1.193/admin
      description: DNS server and adblocker.
  - Synology NAS:
      icon: synology-dsm
      href: http://sleeper-service.home:5000
      ping: http://sleeper-service.home:5000
      description: Primary NAS.
