apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - secret.yaml
  - account.yaml
  - role.yaml
  - service.yaml
  - deployment.yaml
  - ingress.yaml

configMapGenerator:
  - name: homepage
    namespace: homepage
    files:
      - kubernetes.yaml=config/kubernetes.yaml
      - settings.yaml=config/settings.yaml
      - bookmarks.yaml=config/bookmarks.yaml
      - services.yaml=config/services.yaml
      - widgest.yaml=config/widgets.yaml
      - docker.yaml=config/docker.yaml
