- Services:
  - 2FA:
      icon: mdi-two-factor-authentication
      href: https://2fa.hl.ancalagon.black
      ping: https://2fa.hl.ancalagon.black
      description: Internal 2FA generator.

  - Argo CD:
      icon: argocd.png
      href: https://argocd.hl.ancalagon.black
      ping: https://argocd.hl.ancalagon.black
      description: GitOps deploys for kubernetes cluster.

  - Concourse Papercode:
      icon: concourse.png
      href: http://ci.papercode.net:8080
      ping: http://ci.papercode.net:8080
      description: Papercode CI server.

  - Dokuwiki:
      icon: dokuwiki.png
      href: https://dokuwiki.hl.ancalagon.black
      ping: https://dokuwiki.hl.ancalagon.black
      description: Wiki.

  - Gitea:
      icon: gitea.png
      href: https://gitea.hl.ancalagon.black
      ping: https://gitea.hl.ancalagon.black
      description: Git server/package host.

  - Grafana:
      icon: grafana.png
      href: http://monitoring.home:3000
      ping: http://monitoring.home:3000
      description: Metrics visualization.

  - Jellyfin:
      icon: jellyfin.png
      href: http://chiark.home:8096
      ping: http://chiark.home:8096
      description: Media server.

  - Miniflux:
      icon: miniflux-light.png
      href: https://miniflux.hl.ancalagon.black
      ping: https://miniflux.hl.ancalagon.black
      description: RSS aggregator.

  - ntfy:
      icon: ntfy-light.png
      href: https://ntfy.hl.ancalagon.black
      ping: https://ntfy.hl.ancalagon.black
      description: Internal Pub/Sub notifications.

  - Paperless:
      icon: paperless-ngx.png
      href: https://paperless.hl.ancalagon.black
      ping: https://paperless.hl.ancalagon.black
      description: Document archive.

  - Prometheus:
      icon: prometheus.png
      href: http://monitoring.home:9090/targets
      ping: http://monitoring.home:9090/graph
      description: Monitoring and alerting.

  - Proxmox:
      icon: proxmox-light.png
      href: https://vavatch.home:8006
      ping: https://vavatch.home:8006
      description: virtual environments.
      # widget:
      #   type: proxmox
      #   url: https://vavatch.home:8006
      #   username: "{{HOMEPAGE_VAR_PROXMOX_USER}}"
      #   password: "{{HOMEPAGE_VAR_PROXMOX_TOKEN}}"
      #   fields: ["vms", "resources.cpu", "resources.mem"]

  - Stump:
      icon: /icons/stump-logo--irregular.png
      href: https://stump.hl.ancalagon.black
      ping: https://stump.hl.ancalagon.black
      description: Digital book, comic, and OPDS server.

  - tandoor:
      icon: tandoor.png
      href: https://tandoor.ancalagon.black
      ping: https://tandoor.ancalagon.black
      description: Recipe database and meal planning.

  - Trilium:
      icon: trilium.png
      href: https://trilium.hl.ancalagon.black
      ping: https://trilium.hl.ancalagon.black
      description: Notes.

- Media requests:
  - Jellyseerr:
      icon: jellyseerr.png
      href: https://jellyseerr.hl.ancalagon.black
      ping: https://jellyseerr.hl.ancalagon.black
      description: Media requests.
      widget:
        type: jellyseerr
        url: https://jellyseerr.hl.ancalagon.black
        key: "{{HOMEPAGE_VAR_JELLYSEERR_KEY}}"
        fields: ["approved", "available"]

  - Readarr:
      icon: readarr.png
      href: https://readarr.hl.ancalagon.black
      ping: https://readarr.hl.ancalagon.black
      description: Book requests.
      widget:
        type: readarr
        url: https://readarr.hl.ancalagon.black
        key: "{{HOMEPAGE_VAR_READARR_KEY}}"
        fields: ["wanted", "queued"]

  - Sonarr:
      icon: sonarr.png
      href: https://sonarr.hl.ancalagon.black
      ping: https://sonarr.hl.ancalagon.black
      description: TV show requests.
      widget:
        type: sonarr
        url: https://sonarr.hl.ancalagon.black
        key: "{{HOMEPAGE_VAR_SONARR_KEY}}"
        fields: ["wanted", "queued"]

  - Radarr:
      icon: radarr-light.png
      href: https://radarr.hl.ancalagon.black
      ping: https://radarr.hl.ancalagon.black
      description: Movie requests.
      widget:
        type: radarr
        url: https://radarr.hl.ancalagon.black
        key: "{{HOMEPAGE_VAR_RADARR_KEY}}"
        fields: ["wanted", "missing", "queued"]

  - Prowlarr:
      icon: prowlarr.png
      href: https://prowlarr.hl.ancalagon.black
      ping: https://prowlarr.hl.ancalagon.black
      description: Indexer management.

- Download Clients:
  - MeTube:
      icon: metube.png
      href: https://metube.hl.ancalagon.black
      ping: https://metube.hl.ancalagon.black
      description: YouTube (and others) downloader.

  - qbittorrent:
      icon: qbittorrent.png
      href: http://chiark.home:9077
      ping: http://chiark.home:9077
      description: Torrent client.
      widget:
        type: qbittorrent
        url: http://chiark.home:9077
        username: "{{HOMEPAGE_VAR_QBITTORRENT_USER}}"
        password: "{{HOMEPAGE_VAR_QBITTORRENT_PASS}}"

  - SABnzbd:
      icon: sabnzbd-alt.png
      href: https://sabnzbd.hl.ancalagon.black
      ping: https://sabnzbd.hl.ancalagon.black
      description: Usenet client.
      widget:
        type: sabnzbd
        url: https://sabnzbd.hl.ancalagon.black
        key: "{{HOMEPAGE_VAR_SABNZBD_KEY}}"

- Storage:
  # we're not going to ping these so we don't wake them up
  - lasting-damage:
      icon: synology-dsm
      href: http://lasting-damage.home:5000
      description: Synology DS923+.

  - sleeper-service:
      icon: synology-dsm
      href: http://sleeper-service.home:5000
      description: Synology DS1618+.

  - scrutiny:
      icon: scrutiny-light.png
      href: http://chiark.home:8080
      ping: http://chiark.home:8080
      description: SMART disk monitoring dashboard.
      widget:
        type: scrutiny
        url: http://chiark.home:8080

- Networking:
  - Omada Controller:
      icon: omada.png
      href: https://192.168.10.10
      ping: https://192.168.10.10
      description: Omada admin interface

  - pfSense:
      icon: pfsense.png
      href: https://192.168.10.1
      ping: https://192.168.10.1
      description: Firewall/router/gateway

  - Tailscale Admin Console:
      icon: tailscale-light.png
      href: https://login.tailscale.com/admin/machines
      ping: https://tailscale.com
      description: VPN service dashboard

  - traefik-internal:
      icon: traefik.png
      href: https://traefik.hl.ancalagon.black
      ping: https://traefik.hl.ancalagon.black
      description: internal reverse proxy routing dashboard.

  - traefik-external:
      icon: traefik.png
      href: https://traefik-external.ancalagon.black
      ping: https://traefik-external.ancalagon.black
      description: external reverse proxy routing dashboard.
