apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    spec:
      serviceAccountName: homepage
      automountServiceAccountToken: true
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 192.168.40.1
      enableServiceLinks: true
      containers:
        - name: homepage
          image: "ghcr.io/gethomepage/homepage:latest"
          imagePullPolicy: Always
          env:
            - name: HOMEPAGE_ALLOWED_HOSTS
              value: dash.hl.ancalagon.black
          envFrom:
            - configMapRef:
                name: secret-sentinel
            - secretRef:
                name: homepage-config-secret
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          volumeMounts:
            # - mountPath: /app/config/custom.js
            #   name: homepage-config
            #   subPath: custom.js
            # - mountPath: /app/config/custom.css
            #   name: homepage-config
            #   subPath: custom.css
            - mountPath: /app/config/bookmarks.yaml
              name: homepage-config
              subPath: bookmarks.yaml
            - mountPath: /app/config/docker.yaml
              name: homepage-config
              subPath: docker.yaml
            - mountPath: /app/config/kubernetes.yaml
              name: homepage-config
              subPath: kubernetes.yaml
            - mountPath: /app/config/services.yaml
              name: homepage-config
              subPath: services.yaml
            - mountPath: /app/config/settings.yaml
              name: homepage-config
              subPath: settings.yaml
            - mountPath: /app/config/widgets.yaml
              name: homepage-config
              subPath: widgets.yaml
            - name: logs
              mountPath: /app/config/logs
            - name: homepage-icons
              mountPath: /app/public/icons
            - name: homepage-images
              mountPath: /app/public/images
      volumes:
        - configMap:
            name: homepage-config
          name: homepage-config
        - name: logs
          emptyDir:
            {}
        - name: homepage-icons
          persistentVolumeClaim:
            claimName: homepage-icons-pvc
        - name: homepage-images
          persistentVolumeClaim:
            claimName: homepage-images-pvc
