---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homepage-images-pvc
  namespace: homepage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 200Mi
